// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClqarTI5_cF8ngMJqvwtfzdA10xa_SOJQ',
    appId: '1:203258831706:web:4ccd4dd02118d767254963',
    messagingSenderId: '203258831706',
    projectId: 'rvapp-358c4',
    authDomain: 'rvapp-358c4.firebaseapp.com',
    storageBucket: 'rvapp-358c4.appspot.com',
    measurementId: 'G-7TYCYLZHS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoSRx7fOsmbvOnwdFnsP6zkH0xkfwCD4g',
    appId: '1:203258831706:android:9478f51a8c173d78254963',
    messagingSenderId: '203258831706',
    projectId: 'rvapp-358c4',
    storageBucket: 'rvapp-358c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSocMYR5yM8eOEpGqQDqTz29l5GKHPH9o',
    appId: '1:203258831706:ios:8c55f6f62798bd18254963',
    messagingSenderId: '203258831706',
    projectId: 'rvapp-358c4',
    storageBucket: 'rvapp-358c4.appspot.com',
    iosBundleId: 'com.example.rvApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSocMYR5yM8eOEpGqQDqTz29l5GKHPH9o',
    appId: '1:203258831706:ios:f0dc0fd5e3ca3600254963',
    messagingSenderId: '203258831706',
    projectId: 'rvapp-358c4',
    storageBucket: 'rvapp-358c4.appspot.com',
    iosBundleId: 'com.example.rvApp.RunnerTests',
  );
}
